[links.config.git]
dot-config = "~/.gitconfig"

[links.config.gpg]
"." = "~/.gnupg"

[Clinks.cnfig.tmux]
dot-tmux.conf = "~/tmux.conf"

[links.config.vim]
"." = "~/.vim"
dot-vimrc    = "~/.vimrc"

[links.config.wakatime]
wakatime.cfg = "~"

[links.config.ssh]
"." = "~/.ssh"

[links.config.zsh]
dot-zlogin = "~/.zlogin"
dot-zshenv = "~/.zshenv"
dot-zshrc = "~/.zshrc"

[links.local.state]
cargo = "~/.cargo"
ipython = "~/.ipython"
jupyter = "~/.jupyter"
rustup = "~/.rustup"
rvm = "~/.rvm"
vscode = "~/.vscode"
swiftpm = "~/.swiftpm"

[links.local.var]
npm = "~/.npm"
