# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# My Specials:

[plugins.xdg]
local = "~/Projects/zsh-xdg-plugin"

[plugins.shlog]
local = "~/Projects/zsh-shlog-plugin"

[plugins.brew]
local = "~/Projects/zsh-brew-plugin"

[plugins.paths]
local = "~/Projects/zsh-paths-plugin"

# The Rest:

[plugins.bat]
local = "~/Projects/zsh-bat-plugin"

[plugins.cargo]
local = "~/Projects/zsh-cargo-plugin"

[plugins.my-emacs]
local = "~/Projects/zsh-emacs-plugin"

[plugins.eza]
local = "~/Projects/zsh-eza-plugin"

[plugins.my-fzf]
local = "~/Projects/zsh-fzf-plugin"

[plugins.getopt]
local = "~/Projects/zsh-getopt-plugin"

[plugins.my-git]
local = "~/Projects/zsh-git-plugin"

[plugins.gnupg]
local = "~/Projects/zsh-gnupg-plugin"

[plugins.gsed]
local = "~/Projects/zsh-gsed-plugin"

[plugins.guile]
local = "~/Projects/zsh-guile-plugin"

[plugins.hd]
local = "~/Projects/zsh-hd-plugin"

[plugins.history]
local = "~/Projects/zsh-history-plugin"

[plugins.intelli-shell]
local = "~/Projects/zsh-intelli_shell-plugin"

[plugins.kiro]
local = "~/Projects/zsh-kiro-plugin"

[plugins.less]
local = "~/Projects/zsh-less-plugin"

[plugins.llvm]
local = "~/Projects/zsh-llvm-plugin"

[plugins.mcfly]
local = "~/Projects/zsh-mcfly-plugin"

[plugins.myip]
local = "~/Projects/zsh-myip-plugin"

[plugins.openssh]
local = "~/Projects/zsh-openssh-plugin"

[plugins.orbstack]
local = "~/Projects/zsh-orbstack-plugin"

[plugins.racket]
local = "~/Projects/zsh-racket-plugin"

[plugins.ruby]
local = "~/Projects/zsh-ruby-plugin"

[plugins.rust]
local = "~/Projects/zsh-rust-plugin"

[plugins.rvm]
local = "~/Projects/zsh-rvm-plugin"

[plugins.starship]
local = "~/Projects/zsh-starship-plugin"

[plugins.todo]
local = "~/Projects/zsh-todo-plugin"

[plugins.vim]
local = "~/Projects/zsh-vim-plugin"

[plugins.xcode]
local = "~/Projects/zsh-xcode-plugin"

[plugins.zoxide]
local = "~/Projects/zsh-zoxide-plugin"

# Externals:

[plugins.emacs]
github = "Flinner/zsh-emacs"

[plugins.fzf]
github = "scaryrawr/fzf.zsh"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.functions]
github = "mattmc3/zfunctions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

# The _maybe_ list:
# 
# - https://github.com/singular0/zsh-env-secrets
# - https://github.com/tom-power/fzf-tab-widgets.git

[templates]
BIN_PATH = 'export PATH="{{ dir }}/bin:$PATH"'
bin_path = 'path=( "{{ dir }}/bin" $path )'
